apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: {{ .Values.tag }}
  name: vote-bot
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-bot
      version: {{ .Values.tag }}
  template:
    metadata:
      labels:
        app: vote-bot
        version: {{ .Values.tag }}
    spec:
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: web-svc.emojivoto:80
        image: "{{ .Values.image.bot }}:{{ .Values.tag }}"
        name: vote-bot
        resources:
          requests:
            cpu: 10m
