apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: emoji
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: {{ .Values.tag }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-svc
      version: {{ .Values.tag }}
  template:
    metadata:
      labels:
        app: emoji-svc
        version: {{ .Values.tag }}
    spec:
      containers:
      - name: emoji-svc
        image: "{{ .Values.image.emoji }}:{{ .Values.tag }}"
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
        env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
      serviceAccountName: emoji
