apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: {{ .Values.tag }}
  name: voting
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-svc
      version: {{ .Values.tag }}
  template:
    metadata:
      labels:
        app: voting-svc
        version: {{ .Values.tag }}
    spec:
      containers:
      - name: voting-svc
        env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: "{{ .Values.image.voting }}:{{ .Values.tag }}"
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
      serviceAccountName: voting
