namespace: emojivoto

image:
  web: ghcr.io/buoyantio/emojivoto-web
  emoji: ghcr.io/buoyantio/emojivoto-emoji-svc
  voting: ghcr.io/buoyantio/emojivoto-voting-svc
  bot: ghcr.io/buoyantio/emojivoto-web

tag: v12
